### ISSUE TITLE
[Epic] Add Song View

### ISSUE THREAD

**Issue by celina** [samvelie/song-collector#22]
New tables are needed for the database to provide the "default" set of drop-down values for the Add Song form. The values for these drop downs are not editable and are consistent for all users of the app.

- [x] Create Tables in db #19
- [x] Collect existing values and insert into db tables #20
- [x] Create db queries on songs.js to retrieve dropdown values
- [x] Create Add Song form #21

![add song](https://cloud.githubusercontent.com/assets/58040/24918078/b01b5ac4-1ea4-11e7-9db7-42ca0c260950.png)
