### ISSUE TITLE
[Epic] Toolbar

### ISSUE THREAD

**Issue by celina** [samvelie/song-collector#23]
The Toolbar should have different buttons on different views.

- [x] Add Song view:
  - Cancel
    - discards any changes
    - clears form
    - redirects to previous/View Song view?
    - does not submit anything to database
  - Save 
     - submits additions to database
     - redirects to the new song's View Song view

![add song](https://cloud.githubusercontent.com/assets/58040/24919961/0bf29514-1eab-11e7-80e0-ba048f161556.png)

- [x] View Song view:
  - Edit
    - discards any changes 
     - clears form, redirects to previous/View Song view?
     - does not submit anything to database
  - Print
     - opens a window with print template?
     - function to print using browser's print function
  - Share #24 
     - opens a form to enter email address
     - nodemailer, notation info is emailed
     - clears form and closes on submit
  - Delete 
     - removes song from the database
     - redirects somewhere?

![view song](https://cloud.githubusercontent.com/assets/58040/24919972/17019a5e-1eab-11e7-9048-b513729f13a6.png)

- [x] Edit Song view:
  - Cancel
     - discards any changes
     - clears form
     - redirects to previous/View Song view?
     - does not submit anything to database
  - Save 
     - submits modifications to database
     - redirects to the edited song's View Song view

![edit song alt](https://cloud.githubusercontent.com/assets/58040/24919977/1d193532-1eab-11e7-9a9e-a974a696b245.png)
