### ISSUE TITLE
[Epic] Header

### ISSUE THREAD

**Issue by celina** [samvelie/song-collector#5]
- [x] Logo #5
- [x] Navigation #8 
  - [x] Home/Card View (default) link
  - [x] Add Song link
  - [x] Log in/out link #7 
- [ ] [Stretch] User name and picture #15

**Comment by celina** [comment]
:shipit:
